spring.application.name=StudentResultPage
eureka.client.service-url.defaultZone=https://modifiedsrms-rrbz.onrender.com/eureka/
eureka.instance.lease-renewal-interval-in-seconds = 10
server.port = 1000
logging.level.org.springframework.cloud.openfeign=DEBUG
logging.level.com.example=DEBUG
spring.data.mongodb.uri=mongodb+srv://Arun:Arunda95%21@srms.hb100rs.mongodb.net/srmsDB?retryWrites=true&w=majority
logging.level.org.springframework.security=DEBUG
