spring.application.name=DatabaseService
eureka.client.service-url.defaultZone=https://modifiedsrms-rrbz.onrender.com/eureka/
eureka.instance.lease-renewal-interval-in-seconds = 10
spring.data.mongodb.uri=mongodb+srv://Arun:Arunda95%21@srms.hb100rs.mongodb.net/srmsDB?retryWrites=true&w=majority
server.port = 1001
